package com.essj.clinix.models.enums;

public enum Specialty {
    CLINICO_GERAL,
    PEDIATRIA,
    CARDIOLOGIA,
    DERMATOLOGIA,
    GINECOLOGIA,
    ORTOPEDIA,
    NEUROLOGIA,
    PSIQUIATRIA,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    UROLOGIA,
    REUMATOLOGIA,
    INFECTOLOGIA,
    HEMATOLOGIA,
    ONCOLOGIA,
    NEFROLOGIA,
    PNEUMOLOGIA,
    ANESTESIOLOGIA
}
